//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTarget) DeepCopyInto(out *ClusterTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTarget.
func (in *ClusterTarget) DeepCopy() *ClusterTarget {
	if in == nil {
		return nil
	}
	out := new(ClusterTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProvider) DeepCopyInto(out *KrknOperatorTargetProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProvider.
func (in *KrknOperatorTargetProvider) DeepCopy() *KrknOperatorTargetProvider {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknOperatorTargetProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderList) DeepCopyInto(out *KrknOperatorTargetProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknOperatorTargetProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderList.
func (in *KrknOperatorTargetProviderList) DeepCopy() *KrknOperatorTargetProviderList {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknOperatorTargetProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderSpec) DeepCopyInto(out *KrknOperatorTargetProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderSpec.
func (in *KrknOperatorTargetProviderSpec) DeepCopy() *KrknOperatorTargetProviderSpec {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderStatus) DeepCopyInto(out *KrknOperatorTargetProviderStatus) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderStatus.
func (in *KrknOperatorTargetProviderStatus) DeepCopy() *KrknOperatorTargetProviderStatus {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknTargetRequest) DeepCopyInto(out *KrknTargetRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknTargetRequest.
func (in *KrknTargetRequest) DeepCopy() *KrknTargetRequest {
	if in == nil {
		return nil
	}
	out := new(KrknTargetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknTargetRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknTargetRequestList) DeepCopyInto(out *KrknTargetRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknTargetRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknTargetRequestList.
func (in *KrknTargetRequestList) DeepCopy() *KrknTargetRequestList {
	if in == nil {
		return nil
	}
	out := new(KrknTargetRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknTargetRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknTargetRequestSpec) DeepCopyInto(out *KrknTargetRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknTargetRequestSpec.
func (in *KrknTargetRequestSpec) DeepCopy() *KrknTargetRequestSpec {
	if in == nil {
		return nil
	}
	out := new(KrknTargetRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknTargetRequestStatus) DeepCopyInto(out *KrknTargetRequestStatus) {
	*out = *in
	if in.TargetData != nil {
		in, out := &in.TargetData, &out.TargetData
		*out = make(map[string][]ClusterTarget, len(*in))
		for key, val := range *in {
			var outVal []ClusterTarget
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]ClusterTarget, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.Completed != nil {
		in, out := &in.Completed, &out.Completed
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknTargetRequestStatus.
func (in *KrknTargetRequestStatus) DeepCopy() *KrknTargetRequestStatus {
	if in == nil {
		return nil
	}
	out := new(KrknTargetRequestStatus)
	in.DeepCopyInto(out)
	return out
}
