#!/usr/bin/env bash
set -euo pipefail

package_name=krkn-operator-acm
catalog_repository=${KUBERNETES_OPERATORS_REPOSITORY:-k8s-operatorhub/community-operators}
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
source "$script_dir/catalog-git.sh"

usage() {
  echo "usage: $0 <version> <rendered-bundle>" >&2
  exit 2
}

[[ $# -eq 2 ]] || usage
version=$1
bundle_dir=$2

[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$ ]] || {
  echo "invalid release version: $version" >&2
  exit 2
}
[[ -d "$bundle_dir/manifests" && -f "$bundle_dir/metadata/annotations.yaml" ]] || {
  echo "rendered ACM bundle is incomplete: $bundle_dir" >&2
  exit 1
}
csv_file=$(find "$bundle_dir/manifests" -maxdepth 1 -type f \
  -name '*.clusterserviceversion.yaml' -print -quit)
[[ -n "$csv_file" ]] || {
  echo "rendered ACM bundle does not contain a ClusterServiceVersion manifest" >&2
  exit 1
}

: "${KUBERNETES_OPERATORS_FORK:?KUBERNETES_OPERATORS_FORK must be configured (for example, <owner>/community-operators)}"
: "${GH_TOKEN:?GH_TOKEN must be configured with permission to push to KUBERNETES_OPERATORS_FORK and open upstream PRs}"
[[ "$KUBERNETES_OPERATORS_FORK" =~ ^[^/]+/[^/]+$ ]] || {
  echo "KUBERNETES_OPERATORS_FORK must have the form <owner>/<repository>" >&2
  exit 2
}

fork_owner=${KUBERNETES_OPERATORS_FORK%%/*}
work_dir=$(mktemp -d "${RUNNER_TEMP:-${TMPDIR:-/tmp}}/kubernetes-community-operators.XXXXXX")
trap 'rm -rf "$work_dir"' EXIT

prepare_catalog_checkout \
  "$KUBERNETES_OPERATORS_FORK" \
  "$catalog_repository" \
  "automation/$package_name-$version" \
  "$work_dir/catalog"

package_dir="$work_dir/catalog/operators/$package_name"
version_dir="$package_dir/$version"
[[ ! -e "$version_dir" ]] || {
  echo "catalog version already exists: operators/$package_name/$version" >&2
  exit 1
}

mkdir -p "$version_dir"
cp -R "$bundle_dir/manifests" "$version_dir/manifests"
cp -R "$bundle_dir/metadata" "$version_dir/metadata"

git -C "$work_dir/catalog" add "operators/$package_name/$version"
git -C "$work_dir/catalog" commit -m "operator: update $package_name bundle to $version"
git -C "$work_dir/catalog" push --force-with-lease origin "automation/$package_name-$version"

existing_pr=$(gh pr list \
  --repo "$catalog_repository" \
  --head "$fork_owner:automation/$package_name-$version" \
  --state open \
  --json number \
  --jq '.[0].number // empty')
if [[ -n "$existing_pr" ]]; then
  echo "Updated existing catalog PR #$existing_pr"
  exit 0
fi

body_file="$work_dir/pr-body.md"
cat > "$body_file" <<EOF
## Summary

This submission adds the $package_name Kubernetes bundle $version to OperatorHub.io.

The bundle and manifests were generated by the Krkn Operator ACM release workflow.
The ACM bundle depends on the published krkn-operator package from the same catalog.

## Release

- Source release: https://github.com/krkn-chaos/krkn-operator-acm/releases/tag/v$version
- Operator image: https://quay.io/repository/krkn-chaos/krkn-operator-acm?tag=v$version
EOF

gh pr create \
  --repo "$catalog_repository" \
  --head "$fork_owner:automation/$package_name-$version" \
  --base main \
  --title "operator $package_name ($version)" \
  --body-file "$body_file"
