name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Create multi-node KinD cluster
        uses: redhat-chaos/actions/kind@main
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Copy CRDs from krkn-operator dependency
        run: |
          go mod download github.com/krkn-chaos/krkn-operator
          KRKN_OP_PATH=$(go list -m -f '{{.Dir}}' github.com/krkn-chaos/krkn-operator)
          echo "krkn-operator module path: $KRKN_OP_PATH"
          mkdir -p config/crd/bases
          cp -v "$KRKN_OP_PATH"/config/crd/bases/*.yaml config/crd/bases/

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
